image: 
  name: konstin2/maturin
  entrypoint: [""]

stages:
  - build
  - deploy
 
maturin-build:
  stage: build
  script:
    - maturin build --release
  artifacts:
    paths:
      - target/wheels/*.whl
  cache:
    paths:
      - target/

publish-pypi:
  stage: deploy
  dependencies:
    - maturin-build
  script:
    - pip install -U twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token twine upload --repository-url https://framagit.org/api/v4/projects/${CI_PROJECT_ID}/packages/pypi --verbose target/wheels/*.whl
  needs: ["maturin-build"]
  only:
    - tags

format-check:
  allow_failure: true
  stage: build
  script:
    - cargo fmt -- --check

lint:
  allow_failure: true
  stage: deploy
  script:
    - cargo clippy
  needs: ["maturin-build"]

pages:
  stage: deploy
  script:
  - pip install -U --no-index --find-links=./target/wheels pyrgrow
  - pip install -U sphinx
  - sphinx-build -b html . public
  dependencies:
    - maturin-build
  artifacts:
    paths:
    - public
  only:
    - master
  needs: ["maturin-build"]

#publish:
#  stage: publish
#  script:
#    - maturin publish -u user -p $password
